CREATE TABLE COURSE(
	C_NUMBER smallint UNSIGNED NOT NULL,
  	C_NAME varchar(40) NOT NULL,
  	UNIT tinyint UNSIGNED NOT NULL,
	TEXTBOOK varchar(50),
  	OFFERED_BY tinyint UNSIGNED NOT NULL,
    
  	PRIMARY KEY (C_NUMBER),
  	FOREIGN KEY (OFFERED_BY) REFERENCES DEPARTMENT(D_NUMBER)
);
