CREATE TABLE DEGREE (
    DEGREE_NAME VARCHAR(30) NOT NULL,
    PROFESSOR_SSN CHAR(9) NOT NULL,
    
    PRIMARY KEY (DEGREE_NAME, PROFESSOR_SSN),
    FOREIGN KEY (PROFESSOR_SSN) REFERENCES PROFESSOR(SSN)
);
