CREATE TABLE ENROLLMENT(
    CWID char(9) NOT NULL,
    S_NUMBER tinyint UNSIGNED NOT NULL,
    C_NO smallint UNSIGNED NOT NULL,
    GRADE enum('A+','A','A-','B+','B','B-','C+','C','C-','D+','D','D-','F','IP','P','NP','WD'),

    PRIMARY KEY (CWID, C_NO, S_NUMBER),

    FOREIGN KEY (CWID) REFERENCES RECORDS(CWID),
    FOREIGN KEY (C_NO, S_NUMBER) REFERENCES SECTION(C_NO, S_NUMBER)
);
