CREATE TABLE MINOR(
    CWID char(9) NOT NULL,
    D_NUMBER tinyint UNSIGNED NOT NULL,

    PRIMARY KEY (CWID, D_NUMBER),
    FOREIGN KEY (CWID) REFERENCES RECORDS(CWID),
    FOREIGN KEY (D_NUMBER) REFERENCES DEPARTMENT(D_NUMBER)
);
