CREATE TABLE PREREQUISITE(
    COURSE_NUMBER smallint UNSIGNED NOT NULL,
    PREREQUISITE_NUMBER smallint UNSIGNED NOT NULL,

    PRIMARY KEY (COURSE_NUMBER, PREREQUISITE_NUMBER),
    FOREIGN KEY (COURSE_NUMBER) REFERENCES COURSE(C_NUMBER),
    FOREIGN KEY (PREREQUISITE_NUMBER) REFERENCES COURSE(C_NUMBER),

    CHECK (COURSE_NUMBER <> PREREQUISITE_NUMBER) -- prevents a course from being its own prerequisite
);
