CREATE TABLE RECORD(
    CWID CHAR(9) NOT NULL,
    S_FNAME VARCHAR(20) NOT NULL,
    S_LNAME VARCHAR(20) NOT NULL,
    S_T_AREA_CODE TINYINT UNSIGNED,
    TS_T_NUMBER INT UNSIGNED,
    S_A_STREET VARCHAR(50),
    S_A_CITY VARCHAR(20),
	S_A_STATE CHAR(2),
    S_A_ZIP CHAR(5),
    MAJOR TINYINT UNSIGNED,
    
    PRIMARY KEY (CWID),
    FOREIGN KEY (MAJOR) REFERENCES DEPARTMENT(D_NUMBER)
  );
