CREATE TABLE SECTION(
    S_NUMBER TINYINT UNSIGNED NOT NULL,
    C_NO SMALLINT UNSIGNED NOT NULL,
    CLASSROOM VARCHAR(7),
    NUMBER_OF_SEATS TINYINT UNSIGNED,
    MEET_DAYS SET('M', 'T', 'W', 'Th', 'F', 'St'),
    BEGIN_TIME TIME,
    END_TIME TIME,
    TAUGHT_BY char(9),

    PRIMARY KEY (C_NO, S_NUMBER),
    FOREIGN KEY (C_NO) REFERENCES COURSE(C_NUMBER),
    FOREIGN KEY (TAUGHT_BY) REFERENCES PROFESSOR(SSN)
);
